=== vishal-jathar/RestAssured/rest-assured-api-testing/bin/test/MOCK/com/onmobile/storefront/api/authentication/generatetoken1_0test/request_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "The root schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": {},
    "examples": [
        {
            "tnc_version": 1,
            "privacy_version": 1,
            "gender": "male",
            "msisdn": "qVPZBb26DBueOiHz+uiZlO3Ym0Lgx7UqjcoyPqgcNz+Lr1SX09fLCpc8agf/RO04TGTc6NA9eNztJceBPS6s0hn3WcxMKMffNjuPr5TTX+98JYGDTtyXOpAm8LYB0FK23TrRw5fXvNsPDy4tg/Yb2D3HrQwgGag0VJIVgsUKM+P0Y9XuNmzE4I0P+dn1LoXADkp3JG6v//JgSix02kKFcgijSHCgestJ7bR2CqbH8hjebahIO6lDCkh8VTNLDfnInSEbD/WW8JUh6hxebKbYiEPaQa/XxZJHvDqJlmMj0KM3CO9A3YRHOagOs9dbaOHp0Rx3Hg02jzY2KTq6Dmp07A==",
            "crypto_exchange": {
                "version": "1.0",
                "payload": "RVvvStnwxFd70aBKNJkr4vBrTElF7K7jSGo/ajdFX7czsdI+6q3LHaX+S69qdOjV5XOrVN0p+UM4YwutdEJsHkV0Dp3FHb+O40yYFp4wFwCZ/JheysJMpQMEsdKiIIzzYQ+AYK8mXSmd9xWzLFX4CyWJaMhy6z9K7eRgTMP6SP0fSr6sHCpjcNqVwMxraVrs+dVSFBX4kV2XbrY5GXM6ER8wRzVwMWbmQm2/lRj8DhmnwY84CnjRFFpZV9Mn1RiviZxyb86dpDylrmL8s5sz7VJ2C+5je9Z+r4k6By22dY6s/cNEnLFNZgJCVCYrxaHW3WKvZsL5qmdLAB7F1Nr0hA==",
                "iv": "Y65wlPqX21qAM9fgI9l5GA==",
                "hmac": "EbNB/3CMVh6P7KUIpZsRSOYFK3necbfSpwQJ6sx6vRM=",
                "ctoken": "2f255e99-3a34-4eed-be75-32bb6f3c13f9"
            },
            "languages": [
                "en",
                "hi"
            ]
        }
    ],
    "required": [
        "tnc_version",
        "privacy_version",
        "msisdn",
        "crypto_exchange"
      
    ],
    "properties": {
        "tnc_version": {
            "$id": "#/properties/tnc_version",
            "type": "integer",
            "title": "The tnc_version schema",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
                1
            ]
        },
        "privacy_version": {
            "$id": "#/properties/privacy_version",
            "type": "integer",
            "title": "The privacy_version schema",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
                1
            ]
        },
        "gender": {
            "$id": "#/properties/gender",
            "type": "string",
            "title": "The gender schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "male"
            ]
        },
        "msisdn": {
            "$id": "#/properties/msisdn",
            "type": "string",
            "title": "The msisdn schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "qVPZBb26DBueOiHz+uiZlO3Ym0Lgx7UqjcoyPqgcNz+Lr1SX09fLCpc8agf/RO04TGTc6NA9eNztJceBPS6s0hn3WcxMKMffNjuPr5TTX+98JYGDTtyXOpAm8LYB0FK23TrRw5fXvNsPDy4tg/Yb2D3HrQwgGag0VJIVgsUKM+P0Y9XuNmzE4I0P+dn1LoXADkp3JG6v//JgSix02kKFcgijSHCgestJ7bR2CqbH8hjebahIO6lDCkh8VTNLDfnInSEbD/WW8JUh6hxebKbYiEPaQa/XxZJHvDqJlmMj0KM3CO9A3YRHOagOs9dbaOHp0Rx3Hg02jzY2KTq6Dmp07A=="
            ]
        },
        "crypto_exchange": {
            "$id": "#/properties/crypto_exchange",
            "type": "object",
            "title": "The crypto_exchange schema",
            "description": "An explanation about the purpose of this instance.",
            "default": {},
            "examples": [
                {
                    "version": "1.0",
                    "payload": "RVvvStnwxFd70aBKNJkr4vBrTElF7K7jSGo/ajdFX7czsdI+6q3LHaX+S69qdOjV5XOrVN0p+UM4YwutdEJsHkV0Dp3FHb+O40yYFp4wFwCZ/JheysJMpQMEsdKiIIzzYQ+AYK8mXSmd9xWzLFX4CyWJaMhy6z9K7eRgTMP6SP0fSr6sHCpjcNqVwMxraVrs+dVSFBX4kV2XbrY5GXM6ER8wRzVwMWbmQm2/lRj8DhmnwY84CnjRFFpZV9Mn1RiviZxyb86dpDylrmL8s5sz7VJ2C+5je9Z+r4k6By22dY6s/cNEnLFNZgJCVCYrxaHW3WKvZsL5qmdLAB7F1Nr0hA==",
                    "iv": "Y65wlPqX21qAM9fgI9l5GA==",
                    "hmac": "EbNB/3CMVh6P7KUIpZsRSOYFK3necbfSpwQJ6sx6vRM=",
                    "ctoken": "2f255e99-3a34-4eed-be75-32bb6f3c13f9"
                }
            ],
            "required": [
                "version",
                "payload",
                "iv",
                "hmac",
                "ctoken"
            ],
            "properties": {
                "version": {
                    "$id": "#/properties/crypto_exchange/properties/version",
                    "type": "string",
                    "title": "The version schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        "1.0"
                    ]
                },
                "payload": {
                    "$id": "#/properties/crypto_exchange/properties/payload",
                    "type": "string",
                    "title": "The payload schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        "RVvvStnwxFd70aBKNJkr4vBrTElF7K7jSGo/ajdFX7czsdI+6q3LHaX+S69qdOjV5XOrVN0p+UM4YwutdEJsHkV0Dp3FHb+O40yYFp4wFwCZ/JheysJMpQMEsdKiIIzzYQ+AYK8mXSmd9xWzLFX4CyWJaMhy6z9K7eRgTMP6SP0fSr6sHCpjcNqVwMxraVrs+dVSFBX4kV2XbrY5GXM6ER8wRzVwMWbmQm2/lRj8DhmnwY84CnjRFFpZV9Mn1RiviZxyb86dpDylrmL8s5sz7VJ2C+5je9Z+r4k6By22dY6s/cNEnLFNZgJCVCYrxaHW3WKvZsL5qmdLAB7F1Nr0hA=="
                    ]
                },
                "iv": {
                    "$id": "#/properties/crypto_exchange/properties/iv",
                    "type": "string",
                    "title": "The iv schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        "Y65wlPqX21qAM9fgI9l5GA=="
                    ]
                },
                "hmac": {
                    "$id": "#/properties/crypto_exchange/properties/hmac",
                    "type": "string",
                    "title": "The hmac schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        "EbNB/3CMVh6P7KUIpZsRSOYFK3necbfSpwQJ6sx6vRM="
                    ]
                },
                "ctoken": {
                    "$id": "#/properties/crypto_exchange/properties/ctoken",
                    "type": "string",
                    "title": "The ctoken schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        "2f255e99-3a34-4eed-be75-32bb6f3c13f9"
                    ]
                }
            },
            "additionalProperties": true
        },
        "languages": {
            "$id": "#/properties/languages",
            "type": "array",
            "title": "The languages schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                [
                    "en",
                    "hi"
                ]
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/languages/items",
                "anyOf": [
                    {
                        "$id": "#/properties/languages/items/anyOf/0",
                        "type": "string",
                        "title": "The first anyOf schema",
                        "description": "An explanation about the purpose of this instance.",
                        "default": "",
                        "examples": [
                            "en",
                            "hi"
                        ]
                    }
                ]
            }
        }
    },
    "additionalProperties": true
}

=== vishal-jathar/RestAssured/rest-assured-api-testing/src/test/api/resources/com/vishal/storefront/api/authentication/generatetoken1_0test/req_payload2.json
{
    "tnc_version": 1,
    "privacy_version": 1,
    "gender":"male",
    "msisdn": "qVPZBb26DBueOiHz+uiZlO3Ym0Lgx7UqjcoyPqgcNz+Lr1SX09fLCpc8agf/RO04TGTc6NA9eNztJceBPS6s0hn3WcxMKMffNjuPr5TTX+98JYGDTtyXOpAm8LYB0FK23TrRw5fXvNsPDy4tg/Yb2D3HrQwgGag0VJIVgsUKM+P0Y9XuNmzE4I0P+dn1LoXADkp3JG6v//JgSix02kKFcgijSHCgestJ7bR2CqbH8hjebahIO6lDCkh8VTNLDfnInSEbD/WW8JUh6hxebKbYiEPaQa/XxZJHvDqJlmMj0KM3CO9A3YRHOagOs9dbaOHp0Rx3Hg02jzY2KTq6Dmp07A==",
    "crypto_exchange": {
        "version": "1.0",
        "payload": "RVvvStnwxFd70aBKNJkr4vBrTElF7K7jSGo/ajdFX7czsdI+6q3LHaX+S69qdOjV5XOrVN0p+UM4YwutdEJsHkV0Dp3FHb+O40yYFp4wFwCZ/JheysJMpQMEsdKiIIzzYQ+AYK8mXSmd9xWzLFX4CyWJaMhy6z9K7eRgTMP6SP0fSr6sHCpjcNqVwMxraVrs+dVSFBX4kV2XbrY5GXM6ER8wRzVwMWbmQm2/lRj8DhmnwY84CnjRFFpZV9Mn1RiviZxyb86dpDylrmL8s5sz7VJ2C+5je9Z+r4k6By22dY6s/cNEnLFNZgJCVCYrxaHW3WKvZsL5qmdLAB7F1Nr0hA==",
        "iv": "Y65wlPqX21qAM9fgI9l5GA==",
        "hmac": "EbNB/3CMVh6P7KUIpZsRSOYFK3necbfSpwQJ6sx6vRM=",
        "ctoken": "2f255e99-3a34-4eed-be75-32bb6f3c13f9"
    },
    "languages": [
        "en",
        "hi"
    ]
}
