=== vishal-jathar/RestAssured/rest-assured-api-testing/bin/test/MOCK/com/onmobile/vol/storefront/api/user/getuserinfo1_0test/response_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "The root schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": {},
    "examples": [
        {
            "id": "71009",
            "msisdn": "8990123456",
            "status": "ACTIVE",
            "user_type": "MPCS production",
            "network": "CDMA",
            "tnc_version": 0,
            "privacy_version": 0,
            "current_song_status": "UNREGISTERED",
            "operator_name": "VODAFONE",
            "circle_name": "JAMMU",
            "first_name": "Vishallll",
            "last_name": "Jathar",
            "languages": [
                "en"
            ],
            "time_zone_string": "America/New_York",
            "external_id": "8990123456"
        }
    ],
    "required": [
        "id",
        "external_id",
        "msisdn",
        "status",
        "user_type",
        "network",
        "tnc_version",
        "privacy_version"
    ],
    "properties": {
        "id": {
            "$id": "#/properties/id",
            "type": "string",
            "title": "The id schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "71009"
            ]
        },
        "msisdn": {
            "$id": "#/properties/msisdn",
            "type": "string",
            "title": "The msisdn schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "8990123456"
            ]
        },
        "status": {
            "$id": "#/properties/status",
            "type": "string",
            "title": "The status schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "ACTIVE"
            ]
        },
        "user_type": {
            "$id": "#/properties/user_type",
            "type": "string",
            "title": "The user_type schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "MPCS production"
            ]
        },
        "network": {
            "$id": "#/properties/network",
            "type": "string",
            "title": "The network schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "CDMA"
            ]
        },
        "tnc_version": {
            "$id": "#/properties/tnc_version",
            "type": "integer",
            "title": "The tnc_version schema",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
                0
            ]
        },
        "privacy_version": {
            "$id": "#/properties/privacy_version",
            "type": "integer",
            "title": "The privacy_version schema",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
                0
            ]
        },
        "current_song_status": {
            "$id": "#/properties/current_song_status",
            "type": "string",
            "title": "The current_song_status schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "UNREGISTERED"
            ]
        },
        "operator_name": {
            "$id": "#/properties/operator_name",
            "type": "string",
            "title": "The operator_name schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "VODAFONE"
            ]
        },
        "circle_name": {
            "$id": "#/properties/circle_name",
            "type": "string",
            "title": "The circle_name schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "JAMMU"
            ]
        },
        "first_name": {
            "$id": "#/properties/first_name",
            "type": "string",
            "title": "The first_name schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "Vishallll"
            ]
        },
        "last_name": {
            "$id": "#/properties/last_name",
            "type": "string",
            "title": "The last_name schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "Jathar"
            ]
        },
        "languages": {
            "$id": "#/properties/languages",
            "type": "array",
            "title": "The languages schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                [
                    "en"
                ]
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/languages/items",
                "anyOf": [
                    {
                        "$id": "#/properties/languages/items/anyOf/0",
                        "type": "string",
                        "title": "The first anyOf schema",
                        "description": "An explanation about the purpose of this instance.",
                        "default": "",
                        "examples": [
                            "en"
                        ]
                    }
                ]
            }
        },
        "time_zone_string": {
            "$id": "#/properties/time_zone_string",
            "type": "string",
            "title": "The time_zone_string schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "America/New_York"
            ]
        },
        "external_id": {
            "$id": "#/properties/external_id",
            "type": "string",
            "title": "The external_id schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "8990123456"
            ]
        }
    },
    "additionalProperties": true
}

=== vishal-jathar/RestAssured/rest-assured-api-testing/bin/test/MOCK/com/onmobile/vol/storefront/api/user/updateuserinfo1_0test/req_payload1.json
{
  "id": "71009",
  "msisdn": "8990123456",
  "status": "ACTIVE",
  "user_type": "MPCS production",
  "network": "CDMA",
  "tnc_version": 0,
  "privacy_version": 0,
  "current_song_status": "UNREGISTERED",
  "operator_name": "VODAFONE",
  "circle_name": "JAMMU",
  "time_zone_string": "America/New_York",
  "external_id": "8990123456",
  "languages": ["en", "hi"],
  "first_name": "Vishal"
}
