=== vishal-jathar/RestAssured/rest-assured-api-testing/bin/test/MOCK/com/onmobile/vol/storefront/api/user/getbookmarkstest/response_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "The root schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": {},
    "examples": [
        {
            "offset": 0,
            "size": 3,
            "total_items_count": 3,
            "bookmarks": [
                {
                    "user_id": 71009,
                    "bookmark_id": 2935,
                    "asset": {
                        "subtype": {
                            "type": "ringback_musictune"
                        },
                        "type": "song",
                        "id": 1404
                    },
                    "bookmark_date": "2020-12-03 19:38:28 +0530"
                },
                {
                    "user_id": 71009,
                    "bookmark_id": 2933,
                    "asset": {
                        "subtype": {
                            "type": "ringback_nametune"
                        },
                        "type": "rbtprofiletone",
                        "id": 1405
                    },
                    "bookmark_date": "2020-12-03 19:38:28 +0530"
                },
                {
                    "user_id": 71009,
                    "bookmark_id": 2934,
                    "asset": {
                        "subtype": {
                            "type": "ringback_nametune"
                        },
                        "type": "rbtprofiletone",
                        "id": 1406
                    },
                    "bookmark_date": "2020-12-03 19:38:28 +0530"
                }
            ]
        }
    ],
    "required": [
        "offset",
        "size",
        "total_items_count",
        "bookmarks"
    ],
    "properties": {
        "offset": {
            "$id": "#/properties/offset",
            "type": "integer",
            "title": "The offset schema",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
                0
            ]
        },
        "size": {
            "$id": "#/properties/size",
            "type": "integer",
            "title": "The size schema",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
                3
            ]
        },
        "total_items_count": {
            "$id": "#/properties/total_items_count",
            "type": "integer",
            "title": "The total_items_count schema",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
                3
            ]
        },
        "bookmarks": {
            "$id": "#/properties/bookmarks",
            "type": "array",
            "title": "The bookmarks schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                [
                    {
                        "user_id": 71009,
                        "bookmark_id": 2935,
                        "asset": {
                            "subtype": {
                                "type": "ringback_musictune"
                            },
                            "type": "song",
                            "id": 1404
                        },
                        "bookmark_date": "2020-12-03 19:38:28 +0530"
                    },
                    {
                        "user_id": 71009,
                        "bookmark_id": 2933,
                        "asset": {
                            "subtype": {
                                "type": "ringback_nametune"
                            },
                            "type": "rbtprofiletone",
                            "id": 1405
                        },
                        "bookmark_date": "2020-12-03 19:38:28 +0530"
                    }
                ]
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/bookmarks/items",
                "anyOf": [
                    {
                        "$id": "#/properties/bookmarks/items/anyOf/0",
                        "type": "object",
                        "title": "The first anyOf schema",
                        "description": "An explanation about the purpose of this instance.",
                        "default": {},
                        "examples": [
                            {
                                "user_id": 71009,
                                "bookmark_id": 2935,
                                "asset": {
                                    "subtype": {
                                        "type": "ringback_musictune"
                                    },
                                    "type": "song",
                                    "id": 1404
                                },
                                "bookmark_date": "2020-12-03 19:38:28 +0530"
                            }
                        ],
                        "required": [
                            "user_id",
                            "bookmark_id",
                            "asset",
                            "bookmark_date"
                        ],
                        "properties": {
                            "user_id": {
                                "$id": "#/properties/bookmarks/items/anyOf/0/properties/user_id",
                                "type": "integer",
                                "title": "The user_id schema",
                                "description": "An explanation about the purpose of this instance.",
                                "default": 0,
                                "examples": [
                                    71009
                                ]
                            },
                            "bookmark_id": {
                                "$id": "#/properties/bookmarks/items/anyOf/0/properties/bookmark_id",
                                "type": "integer",
                                "title": "The bookmark_id schema",
                                "description": "An explanation about the purpose of this instance.",
                                "default": 0,
                                "examples": [
                                    2935
                                ]
                            },
                            "asset": {
                                "$id": "#/properties/bookmarks/items/anyOf/0/properties/asset",
                                "type": "object",
                                "title": "The asset schema",
                                "description": "An explanation about the purpose of this instance.",
                                "default": {},
                                "examples": [
                                    {
                                        "subtype": {
                                            "type": "ringback_musictune"
                                        },
                                        "type": "song",
                                        "id": 1404
                                    }
                                ],
                                "required": [
                                    "subtype",
                                    "type",
                                    "id"
                                ],
                                "properties": {
                                    "subtype": {
                                        "$id": "#/properties/bookmarks/items/anyOf/0/properties/asset/properties/subtype",
                                        "type": "object",
                                        "title": "The subtype schema",
                                        "description": "An explanation about the purpose of this instance.",
                                        "default": {},
                                        "examples": [
                                            {
                                                "type": "ringback_musictune"
                                            }
                                        ],
                                        "required": [
                                            "type"
                                        ],
                                        "properties": {
                                            "type": {
                                                "$id": "#/properties/bookmarks/items/anyOf/0/properties/asset/properties/subtype/properties/type",
                                                "type": "string",
                                                "title": "The type schema",
                                                "description": "An explanation about the purpose of this instance.",
                                                "default": "",
                                                "examples": [
                                                    "ringback_musictune"
                                                ]
                                            }
                                        },
                                        "additionalProperties": true
                                    },
                                    "type": {
                                        "$id": "#/properties/bookmarks/items/anyOf/0/properties/asset/properties/type",
                                        "type": "string",
                                        "title": "The type schema",
                                        "description": "An explanation about the purpose of this instance.",
                                        "default": "",
                                        "examples": [
                                            "song"
                                        ]
                                    },
                                    "id": {
                                        "$id": "#/properties/bookmarks/items/anyOf/0/properties/asset/properties/id",
                                        "type": "integer",
                                        "title": "The id schema",
                                        "description": "An explanation about the purpose of this instance.",
                                        "default": 0,
                                        "examples": [
                                            1404
                                        ]
                                    }
                                },
                                "additionalProperties": true
                            },
                            "bookmark_date": {
                                "$id": "#/properties/bookmarks/items/anyOf/0/properties/bookmark_date",
                                "type": "string",
                                "title": "The bookmark_date schema",
                                "description": "An explanation about the purpose of this instance.",
                                "default": "",
                                "examples": [
                                    "2020-12-03 19:38:28 +0530"
                                ]
                            }
                        },
                        "additionalProperties": true
                    }
                ]
            }
        }
    },
    "additionalProperties": true
}

=== vishal-jathar/RestAssured/rest-assured-api-testing/src/test/api/resources/MOCK/com/vishalDev/vol/storefront/api/user/getbookmarkstest/match_response1.json
{
    "offset": 0,
    "size": 3,
    "total_items_count": 3,
    "bookmarks": [
        {
            "user_id": 71009,
            "bookmark_id": 2935,
            "asset": {
                "subtype": {
                    "type": "ringback_musictune"
                },
                "type": "song",
                "id": 1404
            },
            "bookmark_date": "2020-12-03 19:38:28 +0530"
        },
        {
            "user_id": 71009,
            "bookmark_id": 2933,
            "asset": {
                "subtype": {
                    "type": "ringback_nametune"
                },
                "type": "rbtprofiletone",
                "id": 1405
            },
            "bookmark_date": "2020-12-03 19:38:28 +0530"
        },
        {
            "user_id": 71009,
            "bookmark_id": 2934,
            "asset": {
                "subtype": {
                    "type": "ringback_nametune"
                },
                "type": "rbtprofiletone",
                "id": 1406
            },
            "bookmark_date": "2020-12-03 19:38:28 +0530"
        }
    ]
}
